version: '3.8'

networks:
  rotten_network:
    driver: bridge 

volumes:
  mongodb_vol:

services:
  rotten-potatoes:
    image: jeansousa/rotten-potatoes:v1
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongousr
      MONGODB_PASSWORD: mongopwd
    ports:
      - 5000:5000
    networks:
      - rotten_network

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongousr
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - rotten_network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongousr
      MONGO_INITDB_ROOT_PASSWORD: mongopwd 
    volumes:
      - mongodb_vol:/data/db
    ports:
      - 27017:27017
    networks:
      - rotten_network